site_name: 'CliFin'

theme:
  name: 'material'

nav:
  - Introduction: index.md
  - User Guide:
      - Introduction : introduction.md
      - Installation: installation.md
  - Tutorials:
      - Overview: overview.md
      - Python Introduction: python_introduction.md
      - Cash Flow Projection: cash_flow_projection.md
      - Risk Factor: risk_factor.md
      - Asset Valuation under Climate Scenarios: asset_valuation.md
  - API Reference: api_reference.md
         
      
      
