
site_name: "CliFin"
theme:
  name: 'material'

nav:
  - Introduction: index.md
  - User Guide:
      - Overview: introduction.md
      - Installation: installation.md
      - API Reference: api_reference.md
